---
title: "STAT 220 Homework 3"
author: "Avery Rosado"
date: "4/22/2021"
output: html_document
---

### Reading: Section 3.1, 3.2
### Problems for Self-Study: 
* Exercise 3.1, 3.3, 3.5, 3.7 on p.92-93 and Exercise 3.13, 3.15, 3.19, 3.21 on p.109-111. Answers can be found at the end of the book (p.387-388).

# Problems to Turn In:

### 1. Suppose in a certain state, 60% of the people have a Visa credit card, 40% have a MasterCard, and 24% have both. Let V be the event that a randomly selected individual has a Visa credit card, and M be the analogous event for a MasterCard. So P(V) = 0.60, P(M) = 0.40, and P(V and M) = 0.24.

#### (a) What is the probability that the randomly selected individual has at least one of the two types of cards?
```{R}
# find P (A ∪ B)
# P (A ∪ B) = P (A) + P (B) − P (A ∩ B)
pv <- 0.6 #a 
pm <- 0.4 #b
pvm <- 0.25
prob <- pv+pm-pvm
print(paste(prob, "is the probability that the randomly selected individual has at least one of the two types of cards."))
```

### (b) What is the probability that the randomly selected individual has neither type of credit card?
```{R}
pv <- 0.6 #a 
pm <- 0.4 #b
pvm <- 0.25
# P[(A ∪ B)′] = 1 − P(A ∪ B)
prob <- 1-pvm
print(paste(prob, "is the probability that the randomly selected individual has neither type of credit card."))
```

### (c) What is the probability that the randomly selected individual has a MasterCard but no Visa credit card?
```{R}
pv <- 0.6 #a 
pm <- 0.4 #b
pvm <- 0.25
# P(A∩B′)=P(A)−P(A∩B)
prob <- pv-pvm
print(paste(prob," is the probability that the randomly selected individual has a MasterCard but no Visa credit card."))
```

### (d) If the randomly selected individual is known to have a MasterCard, what is probability that he/she also has a Visa card?
```{R}
pv <- 0.6 #a 
pm <- 0.4 #b
pvm <- 0.25
# P(A|B) = P(A and B)/P(A)
prob <- pvm/pm
print(paste(prob, "is the probability that they also have a Visa Card."))
```
### (e) If the randomly selected individual is known to have no MasterCard, what is probability that he/she has a Visa card?
```{R}
# given M, find P(V)?
# P(V|M) = P(V and M)/P(V)
prob <- pvm/pv
print(paste(prob, "is the probability that they also have a MasterCard."))
```

#### (f) Are the events V and M independent? Explain briefly.
ANS: V and M are two dependent events. If they were independent, then P(V and M) would be equal to the product of P(V) and P(M). See below:
```{R}
pv <- 0.6 #a 
pm <- 0.4 #b

product <- pv*pm
product
```
It is not that case that P(VM)=PV(V)*P(M). Therefore the two events are dependent. 
#### (g) Are the events V^c and M^c disjoint? Explain briefly.
```{R}
# Does P(A ∪ B)=P(A) +P(B) ?
pv <- 0.6 #a 
pm <- 0.4 #b
pvm <- 0.25
pAUB <- pv+pm-pvm
print(paste(pAUB, " is P(V ∪ M)."))
sum <- pv+pm
print(paste(sum," is the sum of probabilities."))
```
Given the inequality illustrated above, the events V^c and M^c are not disjoint. It is not the case that either is mutually exclusive. 
### 2. A 6-face die is rolled 4 times. The six faces of the die have 1, 2, 3, 4, 5, 6 spots respectively. The die is fair meaning that all six faces are equally likely to come up. Find the probability of the following outcomes

#### (a) All 4 rolls show 3 or more spots
```{R}
p3ormore <- 4/6
presult <- (p3ormore)^4
print(paste(presult, " is the probability that all 4 rolls show 3 or more spots."))
```
#### (b) None of the 4 rolls show 3 or more spots. That is, all 4 rolls show 1 or 2 spots.
```{R}
pnone3ormore <- 2/6
presult <- (pnone3ormore)^4
print(paste(presult, " is the probability that none of the 4 rolls show 3 or more spots."))
```
#### (c) Six-spot comes up at least once in 4 rolls
```{R}
pno6 <- (5/6)^4
p6alo <- 1-pno6
print(paste(p6alo, " is the probability that the six-spot comes up at least once in 4 rolls."))
```
### 3. Five cards are drawn at random without replacement from a well-shuffled deck of poker cards

#### (a) Find the probability that the 5th card is a queen, given that the first 4 cards are 3 Kings and a Queen.
ANS: 3 less face cards; 3 remaining Queens; 49 remaining cards in the deck as a result of the given statement. Therefore:
```{R}
# P(queen|[given statement]) = 3/49
result <- 3/49
print(paste(result, " is the probability that the 5th card is a Queen."))
```
#### (b) Find the probability that the first 3 cards are Kings and the next two cards are the Queens. You may leave the answer as a product of fractions.
```{R}
# 52 cards in a deck
# 4 per face card (ie. Kings and Queens)
probability <- 4/52*3/51*2/50*4/49*3/48
print(paste(probability," is the probability that the first 3 cards are Kings and the next two cards are the Queens."))

```

### 4. Health coverage, relative frequencies. The Behavioral Risk Factor Surveillance System (BRFSS) is an annual telephone survey designed to identify risk factors in the adult population and report emerging health trends. The following table displays the distribution of health status of respondents to this survey(excellent, very good, good, fair, poor) and whether or not they have health insurance.'

#### (a) Are being in excellent health and having health coverage mutually exclusive?
ANS: No mutual exclusivityl; 20.99% of adults are in excellent health and have health coverage.
#### (b) What is the probability that a randomly chosen individual has excellent health?
ANS: 23.29% probability that a randomly chosen individual has excellent health.
#### (c) What is the probability that a randomly chosen individual has excellent health given that he has health coverage?
```{R}
pexcellent_yes <- .2099
yes_total <- 0.8738
probability <- pexcellent_yes/yes_total
print(paste("ANS: ", probability, " is the probability that a randomly chosen individual has excellent health given that he has health coverage."))
```
#### (d) What is the probability that a randomly chosen individual has excellent health given that he doesn’t have health coverage?
```{R}
pexcellent_no <- 0.0230
no_total <- 0.1262
probability <- pexcellent_no/no_total
print(paste("ANS: ", probability, " is the probability that a randomly chosen individual has excellent health given that he doesn’t have health coverage."))
```
#### (e) Do having excellent health and having health coverage appear to be independent?
```{R}
# Probabilities, Product
excellent <- 0.2329
yes <- 0.8738
product <- excellent*yes
print(paste(product, " is the probability that an individual has excellent health TIMES the probability that they have health coverage."))
```
ANS: No, it is unlikely that the two events are independent because the probability illustrated above is not equal to the probability that an individual has excellent health AND health care, which is 0.2099. 

### 5. This problem is from Lab 4: http://www.stat.uchicago.edu/~yibi/s220/labs/lab04.html 
### Suppose a fair coin is tossed a huge number of times. Let H(n) be the number of heads that occur in n tosses. By the law of large numbers, we expect heads to occur in about half of the tosses, i.e., H(n) ≈ n2 . In this problem, we are going to simulate coin tossing in R, and see if this is true.

#### (a) Simulate tossing a fair coin 10000 times. Compute the value of H (n) for n = 1, 2, . . . , 10000 for these 10000 tosses. Make two plots, one with H(n) − n/2 vs. n, and the other with H(n)/n − 0.5 vs. n.
```{R}
coin_outcomes <- c("H","T")
N <- 10000
tosses <- sample(coin_outcomes, size=N, replace=TRUE)
#tosses[1:10000]
numheads <- cumsum(tosses=="H")
# Compute:
#numheads[1:10000]
# Check validity Interpretation I by plotting...
library(mosaic)
# Plot H(n) − n/2 vs. n
qplot(1:N, numheads - (1:N)*.5, geom="line",ylab="H(n)-.5*n",xlab="n")
# Plot H(n)/n − 0.5
qplot(1:N, (numheads/1:N) - 0.5, geom="line",ylab="H(n)/n − 0.5",xlab="n")
```
#### (b) Repeat the simulation in part (a) three times, and include those additional six plots (two plots per simulation). Since the outcomes of the tosses are different, the H(n) and the two plots for the three simulations will be different.
```{R}
library(mosaic)
# Simulation 1
coin_outcomes <- c("H","T")
N <- 10000
tosses <- sample(coin_outcomes, size=N, replace=TRUE)
numheads <- cumsum(tosses=="H")
qplot(1:N, numheads - (1:N)*.5, geom="line",ylab="H(n)-.5*n",xlab="n")
# Plot H(n)/n − 0.5
qplot(1:N, (numheads/1:N) - 0.5, geom="line",ylab="H(n)/n − 0.5",xlab="n")

# Simulation 2
coin_outcomes <- c("H","T")
N <- 10000
tosses <- sample(coin_outcomes, size=N, replace=TRUE)
numheads <- cumsum(tosses=="H")
qplot(1:N, numheads - (1:N)*.5, geom="line",ylab="H(n)-.5*n",xlab="n")
# Plot H(n)/n − 0.5
qplot(1:N, (numheads/1:N) - 0.5, geom="line",ylab="H(n)/n − 0.5",xlab="n")

# Simulation 3
coin_outcomes <- c("H","T")
N <- 10000
tosses <- sample(coin_outcomes, size=N, replace=TRUE)
numheads <- cumsum(tosses=="H")
qplot(1:N, numheads - (1:N)*.5, geom="line",ylab="H(n)-.5*n",xlab="n")
# Plot H(n)/n − 0.5
qplot(1:N, (numheads/1:N) - 0.5, geom="line",ylab="H(n)/n − 0.5",xlab="n")

```
#### (c) From the 8 plots made in part (a) and (b), as n gets large, does H(n) − n/2 seem to approach 0, and does H(n)/n −0.5 seem to approach 0? What’s the right statement of the law of large numbers for coin n tossing? If you are not sure, you can make more simulations and/or increase the number of tosses in each simulation.
ANS: 0 is not necessarily approached as n rises. 0.5 is gradually approached as n rises.
#### (d) Now let’s check the law of large numbers for tossing an UNFAIR coin. Simulate tossing an unfair coin with only 0.2 probability to land heads 10000 times, and compute the values of H(n). This time we expect H(n) ≈ 0.2n, so please plot H(n) − 0.2n vs. n, and plot H(n) − 0.2 vs. n. Repeat this n simulation 4 times (so 8 plots in total). As n gets large, does H(n) − 0.2n seem to approach 0, and does H(n) − 0.2 seem to approach 0? What’s the right statement of the law of large numbers when n tossing such an unfair coin?
```{R}
# Sim 1
coin_outcomes <- c("H","T")
N <- 10000
numheads <- cumsum(tosses=="H")
tosses <- sample(coin_outcomes, size=N, prob=c(0.2,0.8),replace=TRUE)
qplot(1:N, numheads - (1:N)*.2, geom="line",ylab="H(n)-.2*n",xlab="n")
# Plot H(n)/n − 0.5
qplot(1:N, (numheads/1:N) - 0.2, geom="line",ylab="H(n)/n − 0.2",ylim = c(-0.15,0.15),xlab="n")

# Sim 2
coin_outcomes <- c("H","T")
N <- 10000
numheads <- cumsum(tosses=="H")
tosses <- sample(coin_outcomes, size=N, prob=c(0.2,0.8),replace=TRUE)
qplot(1:N, numheads - (1:N)*.2, geom="line",ylab="H(n)-.2*n",xlab="n")
# Plot H(n)/n − 0.5
qplot(1:N, (numheads/1:N) - 0.2, geom="line",ylab="H(n)/n − 0.2",ylim = c(-0.15,0.15),xlab="n")
# Sim 3
coin_outcomes <- c("H","T")
N <- 10000
numheads <- cumsum(tosses=="H")
tosses <- sample(coin_outcomes, size=N, prob=c(0.2,0.8),replace=TRUE)
qplot(1:N, numheads - (1:N)*.2, geom="line",ylab="H(n)-.2*n",xlab="n")
# Plot H(n)/n − 0.5
qplot(1:N, (numheads/1:N) - 0.2, geom="line",ylab="H(n)/n − 0.2",ylim = c(-0.15,0.15),xlab="n")
# Sim 4
coin_outcomes <- c("H","T")
N <- 10000
numheads <- cumsum(tosses=="H")
tosses <- sample(coin_outcomes, size=N, prob=c(0.2,0.8),replace=TRUE)
qplot(1:N, numheads - (1:N)*.2, geom="line",ylab="H(n)-.2*n",xlab="n")
# Plot H(n)/n − 0.5
qplot(1:N, (numheads/1:N) - 0.2, geom="line",ylab="H(n)/n − 0.2",ylim = c(-0.15,0.15),xlab="n")
```
ANS: Once again, 0 is not approached; the proportionb approaches 0.2 instead.
### 6. 
#### (a) A fair 6-face die will be rolled some number of times, and you win if it shows an ace (one spot) 20% or more of the time. Otherwise you lose. Which is better for you to win: 60 rolls, or 600 rolls? Explain. (Note that the probability that a fair 6-face die shows an ace in one roll is 1/6 = 16 23 %.)
ANS: 60 rolls is better because the percentage error is higher for 60 rolls than for 600. Thus there is more chances to stray from the 1/6 (16.67%) chance of rolling an ace once. The greater the likelihood of error, the more likely that the dice will show an ace 20% or more of the time. 

#### (b) As in (a), but you win if the percentage of aces is between 15% and 20% inclusive.
ANS: 600 rolls because the percent error decreases, meaning that the percent of times that an ace will be rolled will be very close to 16.67%, which is between 15% and 20%.
#### (c) As in (a), but you win if the number of aces is within 2 of 1/6 of the number of rolls. In other words, for 60 rolls, you win if you get 8 to 12 aces in 60 rolls. For 600 rolls, you win if you get 98 to 102 aces in 600 rolls.
```{R}
for600 <- .1667*600
for60 <- .1667*60
for600
for60
```
60 rolls because as the number of rolls increases, the likelihood of the number of aces deviating from 16.67% increases. 2 makes up a greater portion of 1-60 than 1-600. Falling within 2 of 10 in 60 rolls is more likely than falling within 2 of 100 for 600 rolls. 

### 7. Suppose that an IRS examiner correctly detects and flags 90% of all erroneous returns that he reviews. In addition, he mistakenly flags 2% of correct returns that he reviews. Suppose that about 20% of the tax returns he reviews contain errors.
#### (a) What proportion of tax returns he reviews are flagged?
```{R}
detectandflag <- .9
mistakeflag <- .02
overallerror <- .2
nonerror <- .8
proportion <- overallerror*detectandflag+nonerror*mistakeflag
print(paste(proportion, " is the proportion of tax returns he revews that are flagged."))
```
#### (b) What proportion of tax returns he flagged actually contain errors?
```{R}
# P(A|B) when A is error and B is flagged overall
errorflagged <- overallerror*detectandflag
flaggedoverall <- overallerror*detectandflag+nonerror*mistakeflag
ans <- errorflagged/flaggedoverall
print(paste(ans, " is the proportion of tax returns he flagged that actually contain errors."))
```

```{R}
vector <- 1:6
f_func <- function(vector){
  min <- min(vec)
  max <- max(vec){
    return(min,max)
  }
}
```
```{R}

sum(dbinom(98:102,600,1/6))
```
```{R}
sum(dbinom(8:12, size=60,p=1/6))
```











