---
title: "STAT 220 Homework 1"
author: "Avery Rosado"
date: "4/1/2021"
output:
  word_document:
    toc: yes
  html_document:
    theme: cosmo
    toc: yes
---
## (Problems for Self-Study)
* Exercise 2.7,2.9,2.11, 2.13 on pp. 56-7 and Exercise 2.27, 2.29 on p.77

# Problems to Turn In

### 1. Exercise 1.10 on p. 20. For part (c), assume that the variable marital has 4 levels: single, married,divorced, and widowed.
a. 
--> Each row of the data matrix represents one resident's information, which includes data on sex, age, marital status, gross income, smoking status, amount smoked on weekends, and amount smoked on weekdays.
b. 
--> 1,691 participants were included in the survey.
c. Variables:
* Sex is a categorical variable, nominal.
* Age is a numerical variable, discrete.
* Marital status is a categorical variable, nominal.
* Gross Income is a categorical variable, ordinal. 
* Smoke is a cateogorical variable, nominal.
* amtWeekends is a numerical variable, discrete.
* amtWeekdays is a numerical variable, discrete.

### 2. Below are sketches of histograms for three variables.
a. In scrambled order, the means are 40, 50, 60. Match the histograms with the means:
* i pairs with mean 60
* ii pairs with mean 50
* iii pairs with mean 40

b. 
* i. The median is bigger than the mean
* ii. The median is about equal to the mean.
* iii. The median is less than the mean

c. Is the SD of histogram (iii) around 5, 15, or 50? Give your reasoning. 
--> The SD of the hist(iii) is around 15. The mean and median occur between, roughly, 30 and 40. A standard deviation of 5 is not sufficient to cover the broad range od density from 0 to 100. The mode occurs at roughly 25 and, as previously mentioned, the mean and median occur between 30 and 40. A standard deviation of 50 is too large to fit into data that is confined to a minimum of 0 and a maximum of 100. Meanwhile, standard deviation of 15 roughly abides by the 68% and 59% rule, which is applicable to this graph because of its unimodal, bell shape. It can be visually approximated that 68% of plotted data falls within 1 standard derivative of the mean, and that 95% falls within 2 standard deviations. 

### 3.  An investigator has a data file showing family incomes for 1,000 subjects in a certain study. The minimum $5,800 a year to $98,600 a year. By accident, the highest income in the file gets changed to $986,000.

a. Does this affect the mean? If so, by how much?
--> This change in maximum family income does affect the mean of the data set. Mean will be elevated significantly.
Below is the formula for mean:
$$ mean = \frac{a_1+a_2+a_3+...+a_n}{n} $$
The value a_n corresponds to the highest recorded family  income, which is increased by this mistake (986,000-98,600=887,400). This value can be placed into the equation above such that:
$$ mean= \frac{887,400}{1,000} = 887.4 $$
Thus, the mean is increased by 887.4 dollars in family income.

b. Does this affect the median? If so, by how much?
--> The median is unaffected by the change in maximal family income. 

### 4. 
```{R}
finalexamscores <- c(42, 53, 63, 76, 76, 78, 80, 85, 86, 86, 87, 87, 88, 88, 89, 89, 90, 91, 92, 94, 95, 95, 96, 96, 97)
# Five-Number Summary
min <- 42
max <- 97
q1 <- 80 # quartile 1
q3 <- 92 # quartile 3
median <- 88
# Boxplot
boxplot(finalexamscores,horizontal=T,main="Student Score Data",xlab="Score out of 100 (%)")
```

* The boundaries of the box represent the first and third quartiles of the data; the left boundary marks the first quartile, while the right marks the third quartile. Quartile 1 is 80(%) and quartile 3 is 92%.
* Meanwhile, the middle line of the box represents the median of the data. The median for the data is 88%. 
* The interquartile range (IQR) can be determined via the following by subtracting $$ Q_3 - Q_1 =$$. Using the data provided, this results in $$ 92 - 80 = 12 $$, IQR=12. 
Alternatively, using R:
```{R}
# Determine fence
iqr_fes <- IQR(finalexamscores)
print(paste(iqr_fes, "is the IQR"))
iqr1.5 <- 1.5*iqr_fes
print(paste("1.5(IQR) =", iqr1.5, "(aka fence)"))
```
* The whiskers extend to the minimum and maximum values of the data set that fall within 1.5(IQR) of the first and third quartilees, respectively. Since 1.5(IQR)=18, the minimum data value that will potentially be extended to by the minimum whisker is Q1-1.5(IQR), 80-18=62. The maximum data value that will be potentiall extended to by the maximum whisker is Q3+1.5(IQR), 92+18=110. Since the plot details the scores of exams, the maximum possible value is 100, and the maximum whisker will only extend to 100 as a result. 
* Outliers fall outside of the maximum and minimal possible values for whiskers outlined above. Overall, Q3+1.5(IQR) marks the upper limit, beyond which any data points are considered outliers, and Q1-1.5(IQR) marks the lower limit. As a result, there are two outliers: 42 and 53, which fall below the lower limit. 

### 5. For each of the following, state whether you expect the distribution to be symmetric, right skewed, or left skewed. Explain your reasoning.
a. Housing prices in a country where 25% of the houses cost below 350,000 dollars, 50% of the houses cost below $450,000, 75% of the houses cost below 1,000,000 dollars and there are a meaningful number of houses that cost more than 6,000,000 dollars.
--> The distribution is likely right skewed. 50% of houses cost below $450,000, while the majority of the remaining houses cost a 1-6+ million dollars. Thus, the graph of this scenario produces a tail in the positive direction. Mean is slightly greater than median. 

b. Number of alcoholic drinks consumed by college students in a given week. Assume that more than half of these students don’t drink since
they are under 21 years old, and only a few drink excessively.
--> The distribution is likely right skewed. The highest frequency of students drink minimally or do not drink at all. Mean and median are shifted in the negative direction as a result and mean is greater than median. 

c. The average on a history exam (scored out of 100 points) was 85, with a standard deviation of 15.
--> The distribution is left skewed. Maximal value of the plot is 100 and minimal value is 0; the scores that students achieved on this exam exist, for the most part, are positively shifted and the bulk of scores take up the top 50% and even the top 25% of possible scores. Thus, mode, median and mean exist in the most positive region of any plot of this data, making the data left skewed. 

### 6. Sir Ronald Aylmer Fisher was an English statistician, evolutionary biologist, and geneticist who worked on a data set that contained sepal length and width, and petal length and width from three species of iris flowers (setosa, versicolor and virginica). There were 50 flowers from each species in the data set.
```{R}
#install.packages("mosaic")
```

```{R}
# call library and use other functions from website referenced
library(mosaic)
data(iris)
str(iris)
# Var: Sepal.Length, Sepal.Width, Petal.Length, Petal.Width ; units cm
# Var: Species (3 categories - setosa, versicolor, virginica)
dim(iris)
```

```{R}
# a. Make a histogram of Petal.Length for all 150 observations. Please try a number of different bin- widths and select one that best displays the distribution of the data.
histogram(~Petal.Length, data=iris,main="Petal Length Observations",width=0.29,col="purple")
```

### a (cont'd). Comment on the shape of the histogram.
There appear to be three distinctive peaks to this histogram, the first occuring between 1 and 2, the second occuring at almost exactly 4, and the third occuring between 4 and 5. There is minimal density in data between petal lengths 2 and 3; rather, the first peak is formed in one cluster of data that exists roughly over domain D:[.8,2] and the second peak is formed in a second cluster that stretches from roughly D:[2.9,7]. 

It is notable that things become slightly more ambiguous when width is decreased slightly:
```{R}
histogram(~Petal.Length, data=iris,main="Petal Length Observations",width=0.25,col="purple")
```

It appears that, in the second "cluster of data, multiple peaks emerge that are identical in density. 

```{R}
# b. Make a boxplot of Petal.Length for all 150 observations. 
boxplot(iris$Petal.Length,horizontal=T,main="Petal Length Observations",col="purple",xlab="Petal Length (cm)")
```

### b (cont'd). What features of the distribution are apparent in the histogram in (a) but not the box plot?
--> The density, or frequency, of data points are apparent in the histogram, but not in the box plot. Thus, the mode(s) and modal shaping of the data cannot be determined using the box plot. Meanwhile, the histogram clearly visualizes unique peaks in frequency/density of the data that reveal whether data is symmetric or skewed. 

```{R}
# c. Make a side-by-side boxplot to compare the petal length of the 3 species of iris. Compare the distributions of the petal length of the 3 species. Use the side-by-side boxplot to explain the shape of the histogram in part (a).
bwplot(Petal.Length ~ Species,data=iris,main="Petal Length Observations for 3 Species",col="purple",ylab="Petal Length (cm)")
```

### c. Compare the distributions of the petal length of the 3 species. Use the side-by-side boxplot to explain the shape of the histogram in part (a).
--> Setosa exhibits the smallest range of data, Versicolor the second smallest, and Virginica the most. Similarly, IQR is greatest in Virginica and smallest in Setosa. It should also be noted that, while Setosa and Versicolor have outliers, Virginica does not. 

Notably, between the plots of each species, there is minimal overlap; Setosa does not overlap with either of the two other species, and merely the whiskers of Versicolor and Virginica overlap, these characteristics are reflected in the three peaks observed in the histogram made for the same data above. The IQR and whiskers of each plot reflect the distribution of data in the histogram above. The gap in data between roughly petal lengths 2 and 3 is reflected in the lack of overlap between the plots for Setosa and Versicolor. The overlap between Versicolor and Virginica are reflected in the closeness of the two peaks in the histogram and in the lack of separation between the tails that extend from each peak in the histogram. 

```{R}
# d, Make a side-by-side boxplot for comparing the sepal length of the 3 species of iris. Compare the distributions of the sepal length of the 3 species.
bwplot(Sepal.Length ~ Species,data=iris,main="Sepal Length Observations for 3 Species",col="purple",ylab="Petal Length (cm)")
```

### d. Compare the distributions of the sepal length of the 3 species.
--> The whiskers of each plot extend for a comparable distance between the 25th and 75th percentiles of each plot. Still, there is some very slight, minor differences that reveal that there is slightly more variance in Versicolor than in Setosa, and slightly more in Virginica than in Versicolor. The IQR's for Virginca and Versicolor are barely distinguishable, and that of Setosa is slightly smaller. Each species' whiskers overlap with the others. Even part of the IQR's of Versicolor and Virginica overlap. 

### e. The iris data set came from a problem in taxonomy: can we find some characteristics that are easy to measure to tell two or more similar species apart? If you were given an iris from one of the 3 species, but not told which one, will you measure the petal length or the sepal length to tell which species it is? Explain your answer.
--> The petal length will be a more beneficial measurement to make if some researcher is given an iris from one of the 3 species without being told which. Each species is somewhat unique; their data points exhibit minimal overlap, meaking measurements far more precise in their capacity to act as identification. This uniqueness does not apply to sepal length, the data for which illustrates a great deal of overlap. 

```{R}
# f. Make a scatter plot of petal length vs. petal width for the three species. Use different colors or shapes of points to represent the three species.
# From the scatter plot you make, if you have an iris plant with Petal Width = 1.5 cm and Petal Length = 4 cm, which species do you think it is?
qplot(Petal.Length,Petal.Width,data=iris,xlab="Petal Length (cm)",ylab="Petal Width (cm)",main="Petal Length vs. Petal Width", color=Species)
```

### f (cont'd). From the scatter plot you make, if you have an iris plant with Petal Width = 1.5 cm and Petal Length = 4 cm, which species do you think it is?
--> It is likely Versicolor.

### 7. Why do some mammals have larger brains for their size? The table below are five rows of the data of the average values of brain weight, body weight, gestation lengths (length of pregnancy), and litter size for 96 species of mammals. The data file is mammals.txt .

```{R}
# a. Make a scatterplot with body weight on the horizontal axis and brain weight on the vertical axis.
setwd("~/Desktop/STAT HW 1")
mammals <- read.table("mammals.txt", header=T)
library(mosaic)
# qplot(Body, Brain, data=mammals)
qplot(Body, Brain, data=mammals, xlab="Body Weight (kg)", ylab="Brain Weight (g)", main="Relation between body weight and brain weight")
```
###  a (cont'd). Can you observe anything from the scatterplot about the relationship between brain weight versus body weight of mammals?
--> The points illustrated above are disorderly. There is a significantly large range. and a similarly large domain over which data has been plotted. Still, in the cluster of points that exusts between body weights [0,~250] and brain weights [0,~600], there may be some relationship. Overall, it seems, in a very vage and uncertain way, that there may be a positive relationship between body weight and brain weight. 

```{R}
# b. Make a scatterplot with body weight on the horizontal axis and brain weight on the vertical axis.
setwd("~/Desktop/STAT HW 1")
mammals <- read.table("mammals.txt", header=T)
# qplot(log(Body), log(Brain), data=mammals)
qplot(log(Body), log(Brain), data=mammals, xlab="log(Body Weight) (log kg)", ylab="log(Brain Weight) (log g)",main="Relation between transformed body and brain weights")
```
### b (cont'd). What does the new scatterplot reveal about relationship between brain weight versus body weight of mammals?
--> The new scatterplot reveals that brain weight and body weight exist in a positive, linear relationship in which brain weight increases as body weight increases and vice versa. 

```{R}
#c. Is brain weight associated the length of pregnancy? Make a scatterplot with gestation length on the horizontal axis and brain weight on the vertical axis.
setwd("~/Desktop/STAT HW 1")
mammals <- read.table("mammals.txt", header=T)

qplot(Gestation, Brain, data=mammals, xlab="Gestation Length", ylab="Brain Weight ( log g)")

# Try transforming one or both variables and make a new scatterplot.
qplot(log(Gestation), log(Brain), data=mammals, xlab="log(Gestation Length)", ylab="log(Brain Weight) (log g)",main="Transformed Brain Weight Over Transformed Gestation Lengths")
```
### c (cont'd). Describe the relationship between brain size and gestation length based on the scatterplot.
There appears to be some semblance of an exponential curve in the data show above. Still, data points are very unorganized and may not be organized around some discernable trend line. Rather, this mention of an exponential curve is  mostly inspired by the singular outlier point that has the highest value in either direction of any point on the plot. It is notable that, between 200 and 400 of the gestation length, there is some dependable growth in body weight, indicating that there may be some positive relation ship. 

### c (cont'd). Does the new scatterplot reveals a clear or simpler relationship?
The new scatterplot of transformed points reveals a positive linear relationship with a considerable amount of straying from any possible trend line. Still, the semblance of any linear relation at all means that a clearer and simpler relationship has been revealed.

```{R}
# d. Make scatterplots to explore the relation between body weight and gestation length. You might want to transform one or both variables.
setwd("~/Desktop/STAT HW 1")
mammals <- read.table("mammals.txt", header=T)
qplot(Gestation, Body, data=mammals, xlab="Gestation Length", ylab="Body Weight (log g)",main="Relation between body weight and gestation length")
# Logarithmic Transformation
qplot(log(Gestation), log(Body), data=mammals, xlab="log(Gestation Length)", ylab="log(Body Weight) (log g)", main="Transformed Body Weight Over Transformed Gestation Lengths")
```

### e. One possible explanation for the positive linear association between (the log of) brain weight and (the log of) gestation length observed in part (c) is that they are both positive linearly associated with (the log of) body weight. Does gestation length have its own effect on brain weight, even after accounting for body weight? In other words, for mammals with similar body weights, do those with longer gestation period tend to have larger brains? To investigate this, we can inspect the relationship between the three variable simultaneously using a coded scatterplot in which the third variable is represented by the size of points:

```{R}
# e. 
qplot(log(Body), log(Brain),xlab="Transformed Body Weight",ylab="Transformed Brain Weight",main="Relation between transformed body and brain weights", size=Gestation, shape=I(1), data=mammals)
```

### e (cont'd). From the coded scatterplot, for mammals with similar body weights, do those with longer gestation period tend to have larger brains?
--> According to the plot above, among mammals with larger body weights, it appears that those with longer gestation periods do generally have greater brain weight (and thereby larger brains). 

```{R}
# f. Make a coded scatterplot similar to the one in part (e) to investigate whether litter size is associated with brain weight, after accounting for body weight.
qplot(log(Body), log(Brain),xlab="Transformed Body Weight",ylab="Transformed Brain Weight",main="Relation between transformed litter size and brain weights", size=Litter, shape=I(1), data=mammals)
```

 
